### ISSUE TITLE
Unicode message seems not work with SSL

### ISSUE THREAD

**Issue by nguyen-viet-hung** [miguelgrinberg/Flask-SocketIO-Chat#18]
Dear Mr. Miguel,

I follow you answer in Flask-SocketIO, I can make the sample Flask-SocketIO-Chat runs in HTTPS but one thing is that unicode messages are not shown correctly, without HTTPS, it works. Please take a view my code at: https://github.com/nguyen-viet-hung/Flask-SocketIO-Chat.git and help me to get over it.

Thanks

**Comment by miguelgrinberg** [comment]
What Python version are you using? Can you show me an example the problem?

**Comment by nguyen-viet-hung** [comment]
I am using Python version 3.6.
Here is the message I sent and received:

Sent message: Tôi thử tiếng Việt
Received message: TÃ´i thá»­ tiáº¿ng Viá»t

**Comment by miguelgrinberg** [comment]
Please try upgrading the Socket.IO JS client to the latest 2.1.0. Let me know if that helps.

**Comment by nguyen-viet-hung** [comment]
After upgrading the Socket.IO JS client to the latest 2.1.1, it works fine. Thanks!
