### ISSUE TITLE
Not working on Google chrome

### ISSUE THREAD

**Issue by shyamsudhir** [miguelgrinberg/Flask-SocketIO-Chat#19]
Hi I tried running the chat application on my MAC book os version 10.13.3 and chrome Version 71.0.3578.98 . 

CFDLMC2286:Flask-SocketIO-Chat-master shyamsudhir$ pip freeze
Click==7.0
Django==1.11.17
dnspython==1.16.0
enum34==1.1.6
eventlet==0.24.1
Flask==1.0.2
Flask-SocketIO==3.2.1
Flask-WTF==0.14.2
greenlet==0.4.15
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
monotonic==1.5
mysqlclient==1.3.14
python-engineio==3.3.1
python-socketio==3.1.2
pytz==2018.7
six==1.12.0
Werkzeug==0.14.1
WTForms==2.2.1

I could just see OK displayed on the browser when typed http://localhost:5000
Same problem with safari 11.0.3

**Comment by miguelgrinberg** [comment]
I just tested the app again and it works fine here. I don't know where this "OK" is coming from, I don't think it comes from this application. Any other detail you can provide? Any errors?

**Comment by shyamsudhir** [comment]
Hi The issue is solved after replacing lolcahost with 127.0.0.1
