### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by c00lhawk607** [miguelgrinberg/Flask-SocketIO-Chat#23]
Is there a way to add a command to kick people? I have tinkered with this and made a /clear command but I also want /kick but I have no clue how to add /kick. Is there a way?

**Comment by miguelgrinberg** [comment]
You can use the `disconnect(sid)` function to remove a client. Besides that, it depends on your application how you implement the `/kick` command.

**Comment by c00lhawk607** [comment]
Could you help me with making this? I can invite you to a repl.it I made and have you help me edit it to add the command. If you can thank you. The link is: https://repl.it/join/yeevqvav-jordandixon1

**Comment by miguelgrinberg** [comment]
Sorry, my time is limited.
