### ISSUE TITLE
Clean install virtualenv error

### ISSUE THREAD

**Issue by jamesbaker1** [miguelgrinberg/Flask-SocketIO-Chat#24]
Thanks so much for the example.

Having this error when performing a clean install in a virtualenv: 
`ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 12)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 12))`

**Comment by jamesbaker1** [comment]
Deleting `pkg-resources==0.0.0` made everything work fine

**Comment by miguelgrinberg** [comment]
Sorry about that, not sure how that package got in the requirements file. It should be fixed now.
