### ISSUE TITLE
Flask-socketio nginx 

### ISSUE THREAD

**Issue by vlad1812** [miguelgrinberg/Flask-SocketIO-Chat#26]
Hi, I've got flask app with chat page, while testing on local machine it works perfect, but when trying deploy online using nginx, gunicorn, chat page not works, got errors in browser console like:
**index.js:83 POST https://*.***.***.***/socket.io/?EIO=3&transport=polling&t=N9qSenM&sid=dd49a7b4091448f2a3fa2b260cd8d569 400 (BAD REQUEST)**
And nginx errors like this:
**connect() failed (111: Connection refused) while connecting to upstream, client: 95.153.48.256, server: 3.137.153.143, request: "GET /socket.io/?EIO=3&transport=polling&t=N9qPpaJ HTTP/1.1", upstream: "http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=N9qPpaJ", host: "3.137.153.143", referrer: "https://3.137.153.143/chat"**
Is it possible to make it alive?
Thanks.

**Comment by miguelgrinberg** [comment]
Did you look at logs from the server? You may need to configure CORS. Normally this is not necessary if the web application and the Socket.IO server come from the same domain, but if your nginx isn't properly configure to forward domains the server may be thinking all request come across origins.

**Comment by vlad1812** [comment]
I'm just beginner in that matter, and probably made some mistakes. 
The configuration in file /etc/nginx/sites-enabled is:

` server{
       listen 80;
       listen 443 ssl;
       ssl on;
      ssl_certificate /etc/ssl/certs/nginx-self-signed.crt;
      ssl_certificate_key /etc/ssl/private/nginx-self-signed.key;
      server_name 3.137.153.143;
      #    return 301 https://$server_name$request_uri;

    location / {
       proxy_set_header Host $host;
       proxy_redirect off;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     add_header 'Access-Control-Allow-Origin' '*' always;
     add_header 'Access-Control-Allow-Methods' '*';
     proxy_pass http://unix:/home/ubuntu/flaskapp/flaskapp.sock;
      #        proxy_pass http://127.0.0.1:8000;
       }

       #    location /socket.io/ {
       #        proxy_http_version 1.1;
       #        proxy_set_header Upgrade $http_upgrade;
       #        proxy_set_header Connection "upgrade";
       #        proxy_redirect off;
       #        proxy_buffering off;
       #        proxy_set_header Host $host;
       #        proxy_set_header X-Real-IP $remote_addr;
       #        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       #        proxy_pass http://127.0.0.1:5000/socket.io/;
       #    }
       }`

**Comment by vlad1812** [comment]
And nginx log errors is:

**connect() failed (111: Connection refused) while connecting to upstream, client: 95.258.48.235, server: 3.137.153.143, request: "GET /socket.io/?EIO=3&transport=polling&t=N9qPpaJ HTTP/1.1", upstream: "http://127.0.0.1:5000/socket.io/?EIO=3&transport=polling&t=N9qPpaJ", host: "3.137.153.143", referrer: "https://3.137.153.143/chat"**

**Comment by vlad1812** [comment]
I learning flask and creating app by your book, which bought recently, I've stuck for many days with flask-socketio, when decided to implement chat into the app...

**Comment by miguelgrinberg** [comment]
Your nginx configuration is not forwarding host information to Flask. There is a file called `proxy_params` that comes with nginx that you have to include to get these default reverse proxy headers set. See the example nginx config I have in the documentation: https://flask-socketio.readthedocs.io/en/latest/#using-nginx-as-a-websocket-reverse-proxy.

But in any case, to get more information any time the server refuses clients you can enable server logs as I suggested before. Just add `logger=True` and `engineio_logger=True` to your `SocketIO()` object. The logs will then be printed to your terminal.

**Comment by vlad1812** [comment]
To print logs in terminal, should I put it here socketio.init_app(flask_app, logger=True, engineio_logger=True),
and then start python command `python app.py`?

**Comment by miguelgrinberg** [comment]
@vlad1812 yes, that should work if you have a `socketio.run()` at the bottom of app.py.

**Comment by vlad1812** [comment]
Finally, in my flask app, for the chat, I use like that :
`  from flask_socketio import SocketIO

from myproject import create_app, socketio

app = create_app()

if __name__ == '__main__':
    socketio.run(app, host='127.0.0.1', port=5001) `

And chat working, is that configuration correct?

**Comment by miguelgrinberg** [comment]
@vlad1812 as far as I can see this is correct. Does it work well?

**Comment by vlad1812** [comment]
Yes, chat page is working. But I use only nginx. Gunicorn disconneceted

**Comment by amansinghlegitt3110** [comment]
server {
    server_name aiqa..com www.aiqa.com;

    location / {
        include proxy_params;
        proxy_pass http://localhost:5000;
        client_max_body_size 100M;
    }

    location /socket.io {
        include proxy_params;
        proxy_pass http://localhost:5000/socket.io;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_hide_header Access-Control-Allow-Origin;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aiqa.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aiqa.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = aiqa.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name aiqa.legitthq.com www.aiqa.com;
    listen 80;
    return 404; # managed by Certbot


}


getting cors error on this configuraation
