### ISSUE TITLE
Example code with Auth key at the time of connect

### ISSUE THREAD

**Issue by rmControls** [miguelgrinberg/Flask-SocketIO-Chat#38]
Thank you for sharing the great example of Flask-SocketIO.... 

I am trying to get authentication token at the time of connect, can you update your sample code with passing Authkey at the time of connect??

**Comment by miguelgrinberg** [comment]
This example does not require authentication. You can look at the documentation for the Socket.IO JS client, and the Python server to see how to pass authentication.

Client docs: https://socket.io/docs/v4/client-api/#iourl
Server docs: https://python-socketio.readthedocs.io/en/latest/server.html#connect-and-disconnect-event-handlers
